<?php

?>

#module-container a {
	color: black;
	text-decoration: none;	
}
#module-container a:hover {
	color: black;
	text-decoration: underline;	
}
#module-container-crow {
	display: table-row
}
#module-container-lcol {
	display: table-cell;
	width: 30%;
}
#module-container-rcol {
	display: table-cell;
	padding: 10px;
}
#module-table {
	display: table;
	width: 100%;
	padding:0;
	margin-bottom: 20px;
}
#module-table #module-row {
	display: table-row;	
	width: 100%;
}
#module-row #module-leftcol {
	display: table-cell;
	width: 83%;
}
#module-row #module-rightcol {
	display: table-cell;
	text-align: right;
}
.module-li {
 
}
.module-li-year {
 list-style: none;
 left: -30px;
 width: 100%;
 font-size:16px;
}
.module-li-month {
 list-style: none;
 left: -30px;
 width: 100%;
 font-size:16px;
 text-indent:20px;
}
.module-li-paren {
 
}
.module-year a {
 color: black;
 text-decoration: none;
}
.module-year a:hover {
 color: black;
 text-decoration: underline;
}
.module-month a {
 color: black;
 text-decoration: none;
}
.module-month a:hover {
 color: black;
 text-decoration: underline;
}
#module-container-inner {
 font-size: 14px;
}
#module-container-inner a {
 color: black;
 text-decoration: none;
}
#module-container-inner a:hover {
 color: #777777; 
}
#module-container-inner h1 {
 line-height: .9em;
}
#module-container-inner h1 a {
 text-decoration: none;
}
#module-container-inner h1 a:hover {
 text-decoration: underline;
}
#module-container-inner-preview-title {
	font-size: 20px;
	font-weight:bold;
	text-align: left;
}
#module-container-inner-preview-author {
	font-size: 16px;
}
#module-container-inner-preview-extra {
	font-size: 16px;	
}
#module-container-inner-preview-category {
	font-size: 16px;
	font-weight: bold;
}
#module-container-inner-preview-width: auto {
	font-size: 16px;
	text-align: left;
	padding: 10px;
	background: white;
	-moz-box-shadow: inset 0 0 8px #888;
	-webkit-box-shadow: inset 0 0 8px #888;
	box-shadow: inset 0 0 8px #888;
	-moz-border-radius: 15px;
	-webkit-border-radius: 15px;
	border-radius: 15px; /* future proofing */
	-khtml-border-radius: 15px; /* for old Konqueror browsers */
	margin-bottom: 10px;
}
#module-container-inner-preview-readmorebtn {
	
}
#module-container-inner-preview-rmbtnrow {
	
}
#module-container-inner-preview-rmbtnlcol {
	
}
#module-container-inner-preview-rmbtnrcol {
	
}
#module-container-inner-preview-rmbtnrcol:hover {
	background: #777777;
	color: white;
}
#module-container-inner-preview-rmbtnrcol a {
	color: white !important;
}
#module-container-inner-preview-rmbtnrcol a:hover {
	color: white !important;
}

#module-full-container-width: autos {
	
}
#module-full-container-width: autos h1 {
	color: black;
	line-height: 1em;
}
.module-full-container-title {
	text-align: left;
	padding-bottom: 10px;
	line-height: .9em;
}
#module-full-container-crow {
	display: table-row
}


#module-a-container-date {
	background: #DFDFDF;
	text-align: center;
	padding-top: 10px;
	padding-bottom: 10px;
	font-weight: bold;
	border: #C9C9C9 thin solid;
	font-size: 18px;
	color: #777;
}
#module-a-container-author {
	padding-top: 10px;
	text-align: right;
}
#module-a-container-author a {
	text-decoration: none;
	color: #C9C9C9;
}
#module-a-container-author a:hover {
	color: #8c4a9d;
}
#module-a-container-comments {
	padding-top: 10px;
	text-align: right;
	color: #C9C9C9;
}
#module-a-container-comments a {
	text-decoration: none;
	color: #C9C9C9;
}
#module-a-container-comments a:hover {
	color: #faca0e;
}
#module-a-container-category {
	padding-top: 10px;
	text-align: right;
	color: #C9C9C9;
}
#module-a-container-category a {
	text-decoration: none;
	color: #C9C9C9;
}
#module-a-container-category a:hover {
	color: #d6002d;
}
#module-a-container-title {
	text-align: left;
	padding-bottom: 10px;
}
#module-a-container-title a {
	font-size: 24px;
	text-decoration: none;
	color: #000;
}
#module-a-container-title a:hover {
	color: #317df0;
}
#module-a-container-width: auto {
	
}
#module-a-container-width: auto a {
	text-decoration: none;
	color: #000;
}
#module-a-container-width: auto a:hover {
	text-decoration: underline;
	color: #000;
}
#module-a-container-tags {
	
}
#module-a-container-tags a {
	
}
#module-a-container-tags a:hover {
	
}
#module-full-a-container-date {
	
}
#module-full-a-container-date-goingtostart {
	
}
#module-full-a-container-author {
	
}
#module-full-a-container-author a {
	
}
#module-full-a-container-author a:hover {
	
}
#module-full-a-container-studio {
	
}
#module-full-a-container-studio a {
	
}
#module-full-a-container-studio a:hover {
	
}
#module-full-a-container-network {
	
}
#module-full-a-container-network a {
	
}
#module-full-a-container-network a:hover {
	
}
#module-full-a-container-comments {
	
}
#module-full-a-container-comments a {
	
}
#module-full-a-container-comments a:hover {
	
}
#module-full-a-container-category {
	
}
#module-full-a-container-category a {
	
}
#module-full-a-container-category a:hover {
	
}
#module-full-a-container-title {
	
}
#module-full-a-container-title a {
	
}
#module-full-a-container-title a:hover {
	
}
#module-full-a-container-width: auto {

}
#module-full-a-container-width: auto a {
	text-decoration: none;
	color: #000;
}
#module-full-a-container-width: auto a:hover {
	text-decoration: underline;
	color: #000;
}
#module-full-a-container-tags {
	padding-top: 10px;
	text-align: left;
	color: #C9C9C9;
}
#module-full-a-container-tags a {
	text-decoration: none;
	color: #C9C9C9;
}
#module-full-a-container-tags a:hover {
	color: #777777;
}
#module-mini-container {
	padding-left: 5px;
}
#module-mini-container-crow {
	display: table-row
}
#module-mini-container-lcol {
	display: table-cell;
	width: 0%;
}
#module-mini-container-rcol {
	display: table-cell;
}
#module-mini-a-container-date {
	background: #DFDFDF;
	text-align: center;
	padding-top: 10px;
	padding-bottom: 10px;
	font-weight: bold;
	border: #C9C9C9 thin solid;
	font-size: 20px;
	color: #777;
}
#module-mini-a-container-author {
	padding-top: 10px;
	text-align: right;
}
#module-mini-a-container-author a {
	text-decoration: none;
	color: #C9C9C9;
}
#module-mini-a-container-author a:hover {
	color: #8c4a9d;
}
#module-mini-a-container-comments {
	padding-top: 10px;
	text-align: right;
}
#module-mini-a-container-comments a {
	text-decoration: none;
	color: #C9C9C9;
}
#module-mini-a-container-comments a:hover {
	color: #faca0e;
}
#module-mini-a-container-category {
	padding-top: 10px;
	text-align: right;
	color: #C9C9C9;
}
#module-mini-a-container-category a {
	text-decoration: none;
	color: #C9C9C9;
}
#module-mini-a-container-category a:hover {
	color: #d6002d;
}
#module-mini-a-container-title {
	text-align: left;
	background: #C13700;
	margin-bottom: 5px;
	border: black thin solid;
	padding: 5px;
	cursor: pointer;
}
#module-mini-a-container-title:hover {
	background: #C17D00;
}
#module-mini-a-container-title a {
	font-size: 14px;
	text-decoration: none;
	color: black;
}
#module-mini-a-container-title a:hover {
	
}
#module-mini-a-container-width: auto {
	
}
#module-mini-a-container-width: auto a {
	text-decoration: none;
	color: #000;
}
#module-mini-a-container-width: auto a:hover {
	text-decoration: underline;
	color: #000;
}
#module-mini-a-container-tags {
	padding-top: 10px;
	text-align: left;
	color: #C9C9C9;
}
#module-mini-a-container-tags a {
	text-decoration: none;
	color: #C9C9C9;
}
#module-mini-a-container-tags a:hover {
	color: #777777;
}